name = "TeaTalk"
uuid = "cdc9f476-1cab-50fd-93e3-967cb34f30bd"
authors = ["Kristof Cools <krcools@gmail.com>"]
version = "0.1.0"

[deps]
CompScienceMeshes = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
